import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elite Luxury Limousine",
  applicationName: "Elite Luxury Limousine",
  referrer: "origin-when-cross-origin",
  category: "service",
  description: `We are a family and locally owned business deeply rooted in tradition serving the Chicago and Milwaukee markets. Where
  integrity and reliability resonate throughout the organization. We look forward to you or your organization joining our family of
  satisfied clients. Professional Chauffeur Services for Seamless Journeys! Book our services and enjoy a stylish and safe ride, regardless of your destination. We provide reliable and experienced chauffeurs ready to meet you at the airport or serve as your personal driver. With a modern fleet, high-quality service, and affordable rates, entrust your journey to professionals and make every ride a hassle-free experience!`,
  metadataBase: new URL("https://eliteluxurylimo.com/"),
  authors: [
    { name: "Alex" },
    { name: "Alex", url: "https://eliteluxurylimo.com/" },
  ],
  openGraph: {
    title: "Elite Luxury Limo Order Ride",
    description:
      "Professional Chauffeur Services for Seamless Journeys! Book our services and enjoy a stylish and safe ride, regardless of your destination. We provide reliable and experienced chauffeurs ready to meet you at the airport or serve as your personal driver. With a modern fleet, high-quality service, and affordable rates, entrust your journey to professionals and make every ride a hassle-free experience!",
    url: "https://eliteluxurylimo.com/",
    siteName: "ELite Luxury Limousine",
    images: [
      {
        url: "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
        width: 800,
        height: 600,
      },
      {
        url: "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
        width: 1800,
        height: 1600,
        alt: "Alex limo",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  creator: "Askar Zhaanbaev",
  publisher: "Alex Limo",
  alternates: {
    canonical: "/",
    languages: {
      "en-US": "/en-US",
    },
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: true,
  },
  keywords: [
    "Transportation Services",
    "Airport Transportation",
    "Shuttle Service",
    "Car Service",
    "Party Bus",
    "Prom Limousine",
    "Wine Tours",
    "Limo Service",
    "Executive Transfers",
    "Limousine Service",
    "Wedding Limousine",
    "Taxi",
    "Chicago party bus",
    "party bus",
    "Chicago limo",
    "limo",
    "limousine",
    "black car",
    "Chicago black car",
    "suburbs limo",
    "suburbs limousine",
    "suburbs black car",
    "sprinter vans",
    "executive vans",
    "stretch limo",
    "stretch limousine",
    "bus",
    "Chicago bus",
    "Chicago stretch limo",
    "Chicago car service",
    "Suburban car service",
    "O’Hare car service",
    "midway car service",
    "executive car service",
    "Chicago limousine",
    "suburban limousine",
    "Barrington car service",
    "lake Barrington car service",
    "Inverness car service",
    "deer park car service",
    "Long Grove car service",
    "Palatine car service",
    "Wilmette car service",
    "Kenilworth car service",
    "Glencoe car service",
    "Winnetka car service",
    "Lake forest car service",
    "Highland Park car service",
    "Lake Bluff car service",
    "Hawthorn Woods car service",
    "Kildeer car service",
    "Chicago black car service",
    "Chicago Party bus",
    "Chicago vans",
    "Chicago Stretch",
    "Chicago wedding car service",
    "Corporate car service Chicago",
    "Hinsdale car service",
    "Elmhurst car service",
    "Chicago sporting events car service",
    "Chicago sorting event limousine",
    "Glen Ellyn car service",
    "Antioch car service",
    "Indiana to O’Hare car service",
    "Wisconsin to O’Hare car service",
    "Wrigley field car service",
    "Cubs car service",
    "Bears car service",
    "Soldier Field car service",
    "United Center car service",
    "Chicago Blackhawks car service",
    "Chicago Bulls car service",
    "Concert car service",
    "McCormick place car service",
    "North Shore car service",
    "Cook county",
    "Chicago convention",
    "Rosemont convention",
    "Schaumburg convention",
    "Tinley Park convention",
    "Chicago",
    "Des Plaines",
    "oak park",
    "Bridgeview",
    "Hoffman Estates",
    "Chicago Heights",
    "Arlington Heights",
    "Glenview",
    "Wilmette",
    "Skokie",
    "Evanston",
    "Rolling Meadows",
    "Palatine",
    "Schaumburg",
    "Oak Lawn",
    "Oak Forest",
    "Northbrook",
    "Winnetka",
    "Wheeling",
    "Kenilworth",
    "River Forest",
    "Matteson",
    "Calumet City",
    "La Grange",
    "Hillside",
    "Mount Prospect",
    "Park Ridge",
    "Rosemont",
    "Alsip",
    "Niles",
    "Melrose Park",
    "South Holland",
    "Palos Heights",
    "Brookfield",
    "Homewood",
    "Glencoe",
    "Morton Grove",
    "Skokie",
    "Lyons",
    "Evergreen Park",
    "Elmwood Park",
    "Western Springs",
    "Barrington",
    "Northfield",
    "Lemont",
    "Orland Park",
    "Tinley Park",
    "Elk Grove Village",
    "Norwood park",
    "Hardwood Heights",
    "River Grove",
    "Jefferson Park",
    "Lake county",
    "Mundelein",
    "Libertyville",
    "Lake Forest",
    "Lake Villa",
    "Vernon Hills",
    "Lake Zurich",
    "Deerfield",
    "Lincolnshire",
    "Highland Park",
    "Buffalo Grove",
    "Grayslake",
    "Lake Bluff",
    "Round Lake",
    "Antioch",
    "Wauconda",
    "Gurnee",
    "Island Lake",
    "Ingleside",
    "Fox Lake",
    "Winthrop Harbor",
    "Wadsworth",
    "Antioch Township",
    "Tower Lakes",
    "Third Lake",
    "Lake Villa township",
    "Hainesville",
    "Riverwoods",
    "Lake Barrington",
    "Long Grove",
    "Kildeer",
    "Deep Park",
    "North Barrington",
    "Hawthorn Woods",
    "Bannockburn",
    "Old Mill Creek",
    "Mettawa",
    "West Deerfield township",
    "Round Lake Heights",
    "Round Lake Park",
    "Shields township",
    "Lindenhurst",
    "Round Lake Beach",
    "Fox River Grove",
    "Volo",
    "Great Lakes",
    "McHenry county",
    "McHenry",
    "Lake in The Hills",
    "Johnsburg",
    "Bull Valley",
    "Prairie Grove",
    "Crystal Lake",
    "Harvard",
    "Richmond",
    "Spring Grove",
    "McCullom Lake",
    "Woodstock",
    "Wonder Lake",
    "Village of Lakewood",
    "Hebron",
    "Holiday Hills",
    "Cary",
    "Marengo",
    "Union",
    "Ringwood",
    "Oakwood Hills",
    "Chemung",
    "Solon Mills",
    "Ridgefield",
    "Trout Valley",
    "Coral",
    "Greenwood",
    "Hartland",
    "Franklinville",
    "Alden",
    "Pistakee Highlands",
    "Riley",
    "DuPage county",
    "Wheaton",
    "Elmhurst",
    "Lisle",
    "Glendale Heights",
    "Warrenville",
    "Clarendon Hills",
    "Downers Grove",
    "Carol Stream",
    "Oak Brook",
    "Winfield",
    "Willowbrook",
    "Oakbrook Terrace",
    "Glen Ellyn",
    "Addison",
    "Westmont",
    "Darien",
    "Wood Dale",
    "Eola",
    "Lombard",
    "West Chicago",
    "Bloomingdale",
    "Villa Park",
    "Itasca",
    "Naperville",
    "Will County",
    "Lockport",
    "Romeoville",
    "Monee",
    "Beecher",
    "Custer Park",
    "New Lennox",
    "Homer Glen",
    "Peotone",
    "Braidwood",
    "Wilton Center",
    "Mokena",
    "Wilmington",
    "Crete",
    "Elwood",
    "Symerton",
    "Shorewood",
    "Crest Hill",
    "Manhattan",
    "Rockdale",
    "Frankfort",
    "Frankfort Square",
    "Crystal Lawns",
    "Goodenow",
    "Willowbrook",
    "Fairmont",
    "Ingalls Park",
    "Andres",
    "Lakewood Shores",
    "Preston Heights",
    "Bolingbrook",
    "Kane county",
    "Geneva",
    "St Charles",
    "Carpentersville",
    "Pingree Grove",
    "Lilly Lake",
    "Sleepy Hollow",
    "Batavia",
    "Sugar Grove",
    "Campton Hills",
    "Kaneville",
    "Virgil",
    "South Elgin",
    "Elgin",
    "Hampshire",
    "West Dundee",
    "Dundee",
    "Burlington",
    "Prestbury",
    "Elburn",
    "North Aurora",
    "Aurora",
    "Gilberts",
    "Big Rock",
    "Valley View",
    "Winnebago county",
    "Winnebago",
    "Machesney Park",
    "New Milford",
    "Rockford",
    "Roscoe",
    "Seward",
    "Pecatonica",
    "South Beloit",
    "Rockton",
    "Durand",
  ],
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
    shortcut:
      "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
    apple:
      "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
    other: {
      rel: "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
      url: "https://res.cloudinary.com/dxvf93ovn/image/upload/v1710474865/alexlimoicons/favicon_et4rd2.ico",
    },
  },
};
export const viewport: Viewport = {
  themeColor: "white",
  initialScale: 1,
  userScalable: true,
  colorScheme: "dark",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="PTy5ePJh3SNOnhel52LBdsIzqccrlclW8T1dcckgxww"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              className: "!bg-slate-700 !text-white",
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
